import Head from "next/head";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create fail3 App</title>
        <meta name="description" content="Generated by fail3" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container component="main">
        <Typography variant="h1">Welcome to fail3</Typography>
      </Container>
    </>
  );
}
